export interface Condo {
  id: string
  code: string
  name: string
  city: string
  admin: string
  units: number
  status: 'Active' | 'Inactive'
}

export const initialCondosMockData: Condo[] = [
  {
    id: 'c-1',
    code: 'BBA-01',
    name: 'Bole Bulbula Block A',
    city: 'Addis Ababa',
    admin: 'Solomon K.',
    units: 48,
    status: 'Active',
  },
  {
    id: 'c-2',
    code: 'GOT-02',
    name: 'Gotera Condominium Block B',
    city: 'Addis Ababa',
    admin: 'Hana T.',
    units: 96,
    status: 'Active',
  },
  {
    id: 'c-3',
    code: 'YKA-04',
    name: 'Yeka Abado Block C',
    city: 'Addis Ababa',
    admin: 'Abebe D.',
    units: 120,
    status: 'Active',
  },
  {
    id: 'c-4',
    code: 'LID-03',
    name: 'Lideta Site 3 Block H',
    city: 'Addis Ababa',
    admin: 'Tsegaye G.',
    units: 72,
    status: 'Inactive',
  },
  {
    id: 'c-5',
    code: 'CLT-01',
    name: 'Cazanchis Luxury Towers',
    city: 'Addis Ababa',
    admin: 'Michael W.',
    units: 32,
    status: 'Active',
  },
  {
    id: 'c-6',
    code: 'SUM-02',
    name: 'Summit Block B',
    city: 'Addis Ababa',
    admin: 'Kidus Y.',
    units: 64,
    status: 'Active',
  },
  {
    id: 'c-7',
    code: 'GER-06',
    name: 'Gerji Sunshine Residence',
    city: 'Addis Ababa',
    admin: 'Etenesh B.',
    units: 40,
    status: 'Active',
  },
  {
    id: 'c-8',
    code: 'LEB-11',
    name: 'Lebu Star Block F',
    city: 'Addis Ababa',
    admin: 'Zenebe T.',
    units: 80,
    status: 'Inactive',
  },
  {
    id: 'c-9',
    code: 'CMT-03',
    name: 'CMC Tsehay Real Estate',
    city: 'Addis Ababa',
    admin: 'Bethelhem M.',
    units: 56,
    status: 'Active',
  },
  {
    id: 'c-10',
    code: 'HAW-01',
    name: 'Lake View Residence',
    city: 'Hawassa',
    admin: 'Dawit A.',
    units: 60,
    status: 'Active',
  },
  {
    id: 'c-11',
    code: 'ADM-02',
    name: 'Palm Grove Complex',
    city: 'Adama',
    admin: 'Genet W.',
    units: 44,
    status: 'Active',
  },
  {
    id: 'c-12',
    code: 'BDR-05',
    name: 'Abay Riverfront Block D',
    city: 'Bahir Dar',
    admin: 'Samuel T.',
    units: 52,
    status: 'Inactive',
  },
  {
    id: 'c-13',
    code: 'MEK-01',
    name: 'Debre Damo Residence',
    city: 'Mekelle',
    admin: 'Berhane K.',
    units: 40,
    status: 'Active',
  },
  {
    id: 'c-14',
    code: 'DIR-03',
    name: 'Alliance Heights',
    city: 'Dire Dawa',
    admin: 'Yonas E.',
    units: 36,
    status: 'Active',
  },
  {
    id: 'c-15',
    code: 'JMA-04',
    name: 'Aba Jifar Block E',
    city: 'Jimma',
    admin: 'Tigist B.',
    units: 48,
    status: 'Active',
  },
  {
    id: 'c-16',
    code: 'BBA-02',
    name: 'Bole Bulbula Block B',
    city: 'Addis Ababa',
    admin: 'Solomon K.',
    units: 48,
    status: 'Active',
  },
  {
    id: 'c-17',
    code: 'GOT-03',
    name: 'Gotera Condominium Block C',
    city: 'Addis Ababa',
    admin: 'Hana T.',
    units: 96,
    status: 'Active',
  },
  {
    id: 'c-18',
    code: 'YKA-05',
    name: 'Yeka Abado Block D',
    city: 'Addis Ababa',
    admin: 'Abebe D.',
    units: 128,
    status: 'Active',
  },
  {
    id: 'c-19',
    code: 'LID-04',
    name: 'Lideta Site 3 Block I',
    city: 'Addis Ababa',
    admin: 'Tsegaye G.',
    units: 72,
    status: 'Active',
  },
  {
    id: 'c-20',
    code: 'CLT-02',
    name: 'Cazanchis Grand Executive',
    city: 'Addis Ababa',
    admin: 'Michael W.',
    units: 28,
    status: 'Active',
  },
  {
    id: 'c-21',
    code: 'SUM-03',
    name: 'Summit Block C',
    city: 'Addis Ababa',
    admin: 'Kidus Y.',
    units: 64,
    status: 'Inactive',
  },
  {
    id: 'c-22',
    code: 'GER-07',
    name: 'Gerji Sunshine Block 2',
    city: 'Addis Ababa',
    admin: 'Etenesh B.',
    units: 40,
    status: 'Active',
  },
  {
    id: 'c-23',
    code: 'LEB-12',
    name: 'Lebu Star Block G',
    city: 'Addis Ababa',
    admin: 'Zenebe T.',
    units: 88,
    status: 'Active',
  },
  {
    id: 'c-24',
    code: 'CMT-04',
    name: 'CMC Tsehay Tower 2',
    city: 'Addis Ababa',
    admin: 'Bethelhem M.',
    units: 60,
    status: 'Active',
  },
  {
    id: 'c-25',
    code: 'HAW-02',
    name: 'Lake View Block B',
    city: 'Hawassa',
    admin: 'Dawit A.',
    units: 48,
    status: 'Active',
  },
  {
    id: 'c-26',
    code: 'ADM-03',
    name: 'Palm Grove Block B',
    city: 'Adama',
    admin: 'Genet W.',
    units: 50,
    status: 'Inactive',
  },
  {
    id: 'c-27',
    code: 'BDR-06',
    name: 'Abay Riverfront Block E',
    city: 'Bahir Dar',
    admin: 'Samuel T.',
    units: 56,
    status: 'Active',
  },
  {
    id: 'c-28',
    code: 'BBA-03',
    name: 'Bole Atlas Heights',
    city: 'Addis Ababa',
    admin: 'Meron A.',
    units: 36,
    status: 'Active',
  },
  {
    id: 'c-29',
    code: 'MKL-02',
    name: 'Romanat Square Complex',
    city: 'Mekelle',
    admin: 'Berhane K.',
    units: 42,
    status: 'Active',
  },
  {
    id: 'c-30',
    code: 'DIR-04',
    name: 'Alliance Heights Block B',
    city: 'Dire Dawa',
    admin: 'Yonas E.',
    units: 40,
    status: 'Active',
  },
  {
    id: 'c-31',
    code: 'JMA-05',
    name: 'Aba Jifar Block F',
    city: 'Jimma',
    admin: 'Tigist B.',
    units: 52,
    status: 'Active',
  },
  {
    id: 'c-32',
    code: 'BBA-04',
    name: 'Bole Medhanialem Towers',
    city: 'Addis Ababa',
    admin: 'Samson N.',
    units: 64,
    status: 'Active',
  },
]
